[package]
name = "dtf_lib_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.6.1"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
serde_valid = "0.16.1"
